### ISSUE TITLE
Reload with unsafe_shutdown fails in 6.3

### ISSUE THREAD

**Issue by danielkasen** [cherweg/logstash-input-s3-sns-sqs#11]
Looks like when I'm using this plugin and have the option in logstash `pipeline.unsafe_shutdown: true` the pipeline can't reload. This worked for 6.2.4 if I was willing to have data loss but blocks any reloading on 6.3.0 Not sure if this is a bug with this plugin or should take it up with the logstash team though. Any thoughts?

**Comment by danielkasen** [comment]
This is the log message that occurs
```{"level":"ERROR","loggerName":"logstash.agent","timeMillis":1529523451980,"thread":"Converge PipelineAction::Reload<s3-elb-elasticsearch-logs>","logEvent":{"message":"Failed to execute action","action":{"metaClass":{"metaClass":{"metaClass":{"action":"PipelineAction::Reload<s3-elb-elasticsearch-logs>","exception":"NoMethodError","message":"undefined method `each' for nil:NilClass","backtrace":["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-sns-sqs-1.6.0/lib/logstash/inputs/s3snssqs.rb:486:in `stop'","/usr/share/logstash/logstash-core/lib/logstash/inputs/base.rb:89:in `do_stop'","org/jruby/RubyArray.java:1734:in `each'","/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:567:in `stop_inputs'","/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:550:in `shutdown'","/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/stop.rb:16:in `block in execute'","/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/stop.rb:15:in `execute'","/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/reload.rb:51:in `block in execute'","/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/reload.rb:50:in `execute'","/usr/share/logstash/logstash-core/lib/logstash/agent.rb:305:in `block in converge_state'"]}}}}}}```

**Comment by cherweg** [comment]
Hey Daniel.
I think i‘ll find the Problem with the Log Message. Please attach the Input part of your config.
I will investigate next week.

regards
Christian

**Comment by danielkasen** [comment]
```input {
  s3snssqs {
    region => "XXXX"
    queue => "XXXXX"
    queue_owner_aws_account_id => "XXXXXX"
    from_sns => false
    codec => plain {
        charset => "ISO-8859-1"
    }
    consumer_threads => 1
    add_field => { "class" => "elb" }
  }
}```

**Comment by christianherweg0807** [comment]
It´s not that easy. I´m still searching for the bug...

sorry
christian

**Comment by danielkasen** [comment]
No worries, I appreciate all the effort you are putting into this.
