### ISSUE TITLE
Support for SQS in a different region

### ISSUE THREAD

**Issue by dhammond22222** [cherweg/logstash-input-s3-sns-sqs#35]
Hello,

When it comes to setting up SNS topics, one benefit is the ability to subscribe to topics from different AWS regions.  In an example scenario:

________________________________________________________________
us-east-1

S3----------event notification--------> us-east-1-SNS-topic
                                                                                             ^
__________________________________________________________|________
us-west-2                                                                           |
                                                                                            |
                                                                                            |
                                                                                            |
SQS <---------------------topic subscription---------

____________________________________________________________________

I noticed the region specification is only declared for the S3 so the plugin assumes the SQS is in the same specified region.

Is this something we support currently that I am missing?

**Comment by cherweg** [comment]
Not supported today. We are working on a solution to configure a region per s3 bucket...maybe we could kill two birds with one stone...

**Comment by christianherweg0807** [comment]
Please see PullRequest: #37
Now you could configure a region for every s3 bucket. 
So your default region should be us-west-2 and the region per bucket us-east-1.

regards
christian

**Comment by mmwilson0** [comment]
Hi, 

To be clear, in order to use the S3-SQS-SNS plugin, does the logstash instance need to exist in the same region as the S3-SQS-SNS configurations? 

I am running into the "uncompleted message at the end of poller loop" error. My Logstash instance exists in US-West-2 and am trying to pull events from various buckets in EU Central & EU West. 

Thanks!

Malcolm
