### ISSUE TITLE
Logstash documentation typos

### ISSUE THREAD

**Issue by klimov-gett** [cherweg/logstash-input-s3-sns-sqs#36]
Didn't find the right place to reprot on elastic logstash docs page https://www.elastic.co/guide/en/logstash/current/plugins-inputs-s3_sns_sqs.html#_getting_help_41. Maybe you have some manner of control over it.

The doc says 
"For plugins not bundled by default, it is easy to install by running bin/logstash-plugin install logstash-input-s3_sns_sqs".
Whereas the proper command is
"bin/logstash-plugin install logstash-input-s3-sns-sqs" (no underscores).

Feel free to close the issue if you don't control the docs on elastic side. Thanks!

**Comment by karenzone** [comment]
@klimov-gett @christianherweg0807 Should be resolved. Thank you both!

**Comment by christianherweg0807** [comment]
See https://www.elastic.co/guide/en/logstash/current/plugins-inputs-s3-sns-sqs.html#_installation_14
