### ISSUE TITLE
Multiple S3 sources into 1 SQS queue

### ISSUE THREAD

**Issue by ckough** [cherweg/logstash-input-s3-sns-sqs#38]
Hi there,

I have a logstash input like so:
input
{
  s3snssqs
  {
    region => "ap-southeast-1"
    queue => "sqs-queue"
    type => "myS3local01"
    codec => json { charset => "UTF-8" }
    sqs_skip_delete => true
    from_sns => false
    s3_options_by_bucket => [
      {
        bucket_name => "myS3local01"
      }
    ]
  }
}
output
{
  elasticsearch
  {
    hosts => ["myelasticsearch.local"]
    index => "%{type}-index"
  }
}

I have multiple pipelines using the same config as above but with the only difference being the type and bucket_name.

The issue is that I find logs being assigned under the wrong index..i.e. myS3local01 logs are found in myS3local02-index.

I suspect it's because the pipeline just take the 1st available message from the queue without checking the bucket name and ingest it. Does this plugin identify which bucket the queue message is coming from?

**Comment by christianherweg0807** [comment]
Multiple Pipelines?
If so, this is a logstash multithreading problem. From my plugincode it is not possible (as fart as i know) to mix input variables...

Addditionally i ddo something like this in my pipelines:
  
`# derive the document type from the s3 folder name
  if ([@metadata][s3][object_folder] and !([@metadata][s3][object_folder] =~ /%{.*}/)) {
    mutate {
      replace => { "type" => "%{[@metadata][s3][object_folder]}" }
    }
  }
`
With this code you should be save...

**Comment by christianherweg0807** [comment]
Ahhh...2nd read...now I understand...
If you have multiple S3 Bucket notifing into one SQS Topic, every pipeline reads the next available message. Doesn´t matter from which S3 Bucket the message is comming from.

You should use multiple SQS queues, if you would like to have different pipelines...
With one pipeline you could use:
```
        s3_options_by_bucket   => [
            { 
                bucket_name => "first-bucket"
                folders => [
                    { 
                        key => ".*ELB-logs.*"
                        codec => "plain"
                        type => "awselb"
                    },
                    { 
                        key => ".*flowlogs.*"
                        codec => "plain"
                        type => "awsvpcflow"
                    }
                ]
            },
            { 
                bucket_name => "second-bucket"
                credentials => { role => "arn:aws:iam::11111111:role" }
                folders => [
                    { 
                        key => ".*"
                        codec => "plain"
                        type => "something"
                    }
                ]
            }
        ]
```

**Comment by ckough** [comment]
Thank you for taking the time to reply.
 May I have 1 final question...😁
When I set "type" for folders like so:
`folders => [
                    { 
                        key => ".*"
                        codec => "plain"
                        type => "**my-awesome-folder**"
                    }
                ]`

Can I actually use the folder's "type" to dynamically create an index?  Example:
`output
{
  elasticsearch
  {
    hosts => ["myelasticsearch.local"]
    index => "%{type}-index"      -----> How do I get "**my-awesome-folder**-index"?
  }
}`

**Comment by christianherweg0807** [comment]
If autocreate indexing is enabled, a new index will be created at the first time of usage.
see: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-creation

regards
christian

**Comment by rubal033** [comment]
Hi

I am also facing similar issue. 
I also have multiple buckets notifying to same SQS. But i wanted to get the logs of different bucket into different indexes.
Is it possible to use the bucket_name in the conditions for the output? Or if can can have different tags with diffrent bucket name and then use them in conditions?

**Comment by cherweg** [comment]
Yes the event is decorated with the Filename, Bucketname and the Path...
Please see:

https://github.com/cherweg/logstash-input-s3-sns-sqs/blob/a1bdb0a5babd3d70d807f6448666f03d47a032eb/lib/logstash/inputs/s3snssqs/log_processor.rb#L72

Von meinem iPhone gesendet

**Comment by christianherweg0807** [comment]
Close because of silence...I think you managed it. :-)
