### ISSUE TITLE
How to configure long-polling?

### ISSUE THREAD

**Issue by pbcole** [cherweg/logstash-input-s3-sns-sqs#39]
Hi,

I will confess at this point to only a limited knowledge of Ruby, so apologies if the answer is obvious with a little more knowledge than I currently have.

We are using this plugin to consume from several queues and buckets - mostly without issue.  Sometimes, we are getting to an empty(ish) queue, and that's leading to a significant number of EmptyReceives.  To reduce the number of EmptyReceives, I was checking for Long Polling, and I've not yet worked out how to configure the plugin to use long polling.  Can you help me work this out?

I see
```
      # long polling; by default we use the queue's setting.
      # A good value is 10 seconds to to balance between a quick logstash
      # shutdown and fewer api calls.
      wait_time_seconds: nil,
```
in the DEFAULT_OPTIONS of class SqsPoller.  But this value doesn't seem to be used.  

The place where I feel we should have wait_time_seconds is in the aws_options_hash which is passed through to the SQS client.  How would I add the value there?

**Comment by pbcole** [comment]
I have found a solution to this by setting the value on the queue.  It would be good to be able to set it easily through the plugin though for times when you either don't want to have it set on the queue (maybe not all consumers will want/need to use long polling), or you don't have access to change the queue configuration.

**Comment by christianherweg0807** [comment]
you are right. I could make it configureable at the next release...
