### ISSUE TITLE
German "Umlaute" are not parsed correctly

### ISSUE THREAD

**Issue by LukasKucharski1887** [cherweg/logstash-input-s3-sns-sqs#46]
Inputfile: valid s3-file, with correct utf8 encoding

Output: Broken "ü" in this case
![image](https://user-images.githubusercontent.com/39726245/91432380-efbf8800-e861-11ea-886b-51ac4a95e0e3.png)

**Comment by christianherweg0807** [comment]
thank you lukas.
This should be fixed in 2.1.1
