### ISSUE TITLE
sqs_delete_on_failure defaults to true,  docs say default is false

### ISSUE THREAD

**Issue by hkelley** [cherweg/logstash-input-s3-sns-sqs#48]
From my logs:

`[logstash.inputs.s3snssqs ] config LogStash::Inputs::S3SNSSQS/@sqs_delete_on_failure = true`

From lib/logstash/inputs/s3snssqs.rb

` config :sqs_delete_on_failure, :validate => :boolean, :default => true`

[docs:](https://github.com/cherweg/logstash-input-s3-sns-sqs/blob/480cf2f5a8fab0d8d217ed04f4647c867865095a/docs/index.asciidoc#plugins-inputs-logstash-input-s3-sns-sqs-sqs_delete_on_failure)

sqs_delete_on_failure       The default value for this setting is FALSE.

**Comment by christianherweg0807** [comment]
Oh you are right. Probably an copyn´paste failure...
Default behaviour is to delete the sqs message if the logprocessor was not able to return in time:
https://github.com/cherweg/logstash-input-s3-sns-sqs/blob/480cf2f5a8fab0d8d217ed04f4647c867865095a/lib/logstash/inputs/sqs/poller.rb#L108-L109

I´ll fix this in the docs.
regards
Christian
