### ISSUE TITLE
SQS messages with different schema,  not using bucket+key+size

### ISSUE THREAD

**Issue by hkelley** [cherweg/logstash-input-s3-sns-sqs#49]
The queue messages I am sent don't conform to the plugin's "schema".   Therefore they never get past preprocessing.  

> [DEBUG][logstash.inputs.s3snssqs ][main] Inside Preprocess: Start {:event=>#<struct Aws::SQS::Types::Message message_id="329a5c5c-e8f8-45e7-87fd-ac74440eb7e8", receipt_handle="AQE......
[DEBUG][logstash.inputs.s3snssqs ][main] Payload in Preprocess:  {:payload=>XXXX}
[DEBUG][logstash.inputs.s3snssqs ][main] [Worker XXX/0] uncompleted message at the end of poller loop. We´ll throw skip_delete. {:message_count=>2874}

Is there a mechanism to customize the preprocessor in poller.rb?

>
{"cid"=>"xxxxxxxxxxxxxxxxxxx",
 "timestamp"=>1599160001104,
 "fileCount"=>4,
 "totalSize"=>85439050,
 "bucket"=>"bucketname",
 "pathPrefix"=>"data/39adb63a-0a31-4215-9b77-4f371fb70f23",
 "files"=>[
	 {"path"=>"data/39adb63a-0a31-4215-9b77-4f371fb70f23/part-00000.gz",
	 "size"=>21439532,
	 "checksum"=>"fa72050c5f932d1530fd1ad28981f734"},
	 {"path"=>"data/39adb63a-0a31-4215-9b77-4f371fb70f23/part-00003.gz",
	 "size"=>21331017,
	 "checksum"=>"16d0b97ef1fb5b70dea7bdb9e968258a"}
	]
}

**Comment by christianherweg0807** [comment]
I´m sorry, but this is not configurable. the preprocessor works on the [AWS Event Message Structure
](https://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html). 
`{  
   "Records":[  
      {  
         "eventVersion":"2.2",
         "eventSource":"aws:s3",
         "awsRegion":"us-west-2",
         "eventTime":The time, in ISO-8601 format, for example, 1970-01-01T00:00:00.000Z, when Amazon S3 finished processing the request,
         "eventName":"event-type",
         "userIdentity":{  
            "principalId":"Amazon-customer-ID-of-the-user-who-caused-the-event"
         },
         "requestParameters":{  
            "sourceIPAddress":"ip-address-where-request-came-from"
         },
         "responseElements":{  
            "x-amz-request-id":"Amazon S3 generated request ID",
            "x-amz-id-2":"Amazon S3 host that processed the request"
         },
         "s3":{  
            "s3SchemaVersion":"1.0",
            "configurationId":"ID found in the bucket notification configuration",
            "bucket":{  
               "name":"bucket-name",
               "ownerIdentity":{  
                  "principalId":"Amazon-customer-ID-of-the-bucket-owner"
               },
               "arn":"bucket-ARN"
            },
            "object":{  
               "key":"object-key",
               "size":object-size,
               "eTag":"object eTag",
               "versionId":"object version if bucket is versioning-enabled, otherwise null",
               "sequencer": "a string representation of a hexadecimal value used to determine event sequence, 
                   only used with PUTs and DELETEs"
            }
         },
         "glacierEventData": {
            "restoreEventData": {
               "lifecycleRestorationExpiryTime": "The time, in ISO-8601 format, for example, 1970-01-01T00:00:00.000Z, of Restore Expiry",
               "lifecycleRestoreStorageClass": "Source storage class for restore"
            }
         }
      }
   ]
}`

I´d recommend you to migrate your format to this standard. If that´s not possible you have to fork this plugin and modify the sources.

regards
Christian

**Comment by hkelley** [comment]
Thank you for confirming.  I am unable to change the SQS message format (vendor-specified) but it seems like I can get what I need by changing a few lines in poller.rb's preprocess().   The rest of the plugin seems to work nicely as-is.

**Comment by hkelley** [comment]
Forked plugin now at:
* https://rubygems.org/gems/logstash-input-crowdstrike_fdr
* https://github.com/hkelley/logstash-input-crowdstrike_fdr
