### ISSUE TITLE
Migration to aws-sdk v3 needed

### ISSUE THREAD

**Issue by holgerjenczewski1007** [cherweg/logstash-input-s3-sns-sqs#69]
In AWS EKS, the plugin running with logstash in a pod does not respect the IAM role provided by the serviceaccount.
Instead, it insists on using the node role of the underlying EC2 instance.

Since a recent version of the AWS CLI in the same pod shows the use of the correct role, it is assumed that upgrading from Ruby AWS SDK v2 to v3 might solve this problem. As v2 is deprecated as of Nov 2020(!), an upgrade is necessary anyway.

**Comment by christianherweg0807** [comment]
Waiting for:
https://github.com/logstash-plugins/logstash-mixin-aws/pull/39

It is not possible to use a aws-sdk version > 2 until mixin is upgrading.

**Comment by bradfordlittooysonos** [comment]
Has anyone come up with a workaround for this in the meantime? 
Thanks!

**Comment by christianherweg0807** [comment]
Since today we have a preview of logstash-integration-aws. So, here we go:

```
declare -a PluginList=("logstash-input-s3-sns-sqs" "logstash-input-s3" "logstash-input-sqs" "logstash-output-s3" "logstash-output-sns" "logstash-output-sqs" "logstash-output-cloudwatch" "logstash-mixin-aws")
LOGSTASH_HOME=${LOGSTASH_HOME:-'.'}
for plugin in ${PluginList[@]}; do
   echo "Try uninstalling plugin ${plugin}"
   ${LOGSTASH_HOME}/bin/logstash-plugin remove $plugin
done

./bin/logstash-plugin install --version 0.1.0.pre logstash-integration-aws 

./bin/logstash-plugin install --version 2.2.0.pre logstash-input-s3-sns-sqs
 ```


```
logstash-integration-aws (0.1.0.pre)
 ├── logstash-codec-cloudfront
 ├── logstash-codec-cloudtrail
 ├── logstash-input-cloudwatch
 ├── logstash-input-s3
 ├── logstash-input-sqs
 ├── logstash-mixin-aws
 ├── logstash-output-cloudwatch
 ├── logstash-output-s3
 ├── logstash-output-sns
 └── logstash-output-sqs

logstash-input-s3-sns-sqs (2.2.0.pre)
