### ISSUE TITLE
Issue Loading Plugin in Logstash >= 8.10.0

### ISSUE THREAD

**Issue by ryanpersaud** [cherweg/logstash-input-s3-sns-sqs#86]
Posting here in case anyone else is running into the same issue.
See: https://github.com/elastic/logstash/issues/15368

**Comment by TheNewdarklabs** [comment]
yes, Im facing the issue in 8.10.
Please let me know if you find any alternative / workaround to fix this

**Comment by TheNewdarklabs** [comment]
@ryanpersaud please let me know if you had a work around for this issue ?

**Comment by ryanpersaud** [comment]
I have not found a workaround for this issue, unfortunately.  It sounds like the fix will have to come from this project since the Logstash folks closed the ticket.

**Comment by cherweg** [comment]
Sorry for the late answer. I’ll try to fix this.Will need about 3 weeks until release.Sorry for that, we are running still on logstash 7.xVon meinem iPhone gesendetAm 06.10.2023 um 08:29 schrieb Rajesh ***@***.***>:﻿
@ryanpersaud please let me know if you had a work around for this issue ?

**Comment by christianherweg0807** [comment]
Successfully registered gem: logstash-input-s3-sns-sqs (2.2.2)

**Comment by christianherweg0807** [comment]
should be fixed now

**Comment by TheNewdarklabs** [comment]
Thank you
